# -*- mode: python ; coding: utf-8 -*-

import sys
from pathlib import Path

block_cipher = None

# Get the project root directory
project_root = Path(__file__).parent

a = Analysis(
    ['install_executable.py'],
    pathex=[str(project_root)],
    binaries=[],
    datas=[
        ('src', 'src'),
        ('config', 'config'),
        ('requirements', 'requirements'),
        ('README.md', '.'),
        ('LICENSE', '.'),
        ('setup.py', '.')
    ],
    hiddenimports=[
        'asyncio',
        'aiohttp',
        'uvloop',
        'psutil',
        'GPUtil',
        'torch',
        'transformers',
        'sentence_transformers',
        'chromadb',
        'langchain',
        'openai',
        'scikit_learn',
        'sklearn',
        'numpy',
        'pandas',
        'matplotlib',
        'seaborn',
        'cryptography',
        'redis',
        'pyyaml',
        'yaml',
        'toml',
        'requests',
        'jinja2',
        'websockets',
        'speech_recognition',
        'pyttsx3',
        'pyaudio',
        'json',
        'sqlite3',
        'threading',
        'multiprocessing',
        'queue',
        'collections',
        'dataclasses',
        'enum',
        'pathlib',
        'typing',
        'functools',
        'itertools',
        'contextlib',
        'concurrent.futures',
        'logging',
        'datetime',
        'time',
        'os',
        'sys',
        'subprocess',
        'platform',
        'shutil',
        'tempfile',
        'urllib',
        'zipfile',
        'tarfile',
        'hashlib',
        'base64',
        'secrets',
        'ssl',
        'socket',
        'http',
        'email',
        'mimetypes',
        'xml',
        'html',
        'csv',
        'configparser',
        'argparse',
        'getpass',
        'glob',
        'fnmatch',
        'linecache',
        'traceback',
        'warnings',
        'weakref',
        'gc',
        'ctypes',
        'struct',
        'array',
        'copy',
        'pickle',
        'shelve',
        'dbm',
        'gzip',
        'bz2',
        'lzma',
        'zlib',
        'binascii',
        'codecs',
        'locale',
        'calendar',
        'decimal',
        'fractions',
        'random',
        'statistics',
        'math',
        'cmath',
        're',
        'string',
        'textwrap',
        'unicodedata',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib.backends._backend_tk',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AI-System-Installer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AI-System-Installer',
)
